# This is a config for E2B sandbox template.
# You can use template ID (ps9b5sxr8drmzyo2rvpl) or template name (vibe-nextjs-test-1757266715) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-1757266715") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-1757266715") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-1757266715')

team_id = "e5edd7f4-e07d-403b-bf13-0926fd4ed545"
start_cmd = "compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-1757266715"
template_id = "ps9b5sxr8drmzyo2rvpl"
